/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminLoginHubRouteImport } from './routes/admin-login-hub'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksIndexRouteImport } from './routes/works/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WorksWorkIdRouteImport } from './routes/works/$workId'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminSiteRouteImport } from './routes/admin/site'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminWorksIndexRouteImport } from './routes/admin/works/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AdminWorksNewRouteImport } from './routes/admin/works/new'
import { Route as AdminPostsNewRouteImport } from './routes/admin/posts/new'
import { Route as AdminWorksWorkIdEditRouteImport } from './routes/admin/works/$workId/edit'
import { Route as AdminPostsPostIdEditRouteImport } from './routes/admin/posts/$postId/edit'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginHubRoute = AdminLoginHubRouteImport.update({
  id: '/admin-login-hub',
  path: '/admin-login-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WorksWorkIdRoute = WorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorksIndexRoute = AdminWorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorksNewRoute = AdminWorksNewRouteImport.update({
  id: '/works/new',
  path: '/works/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorksWorkIdEditRoute = AdminWorksWorkIdEditRouteImport.update({
  id: '/works/$workId/edit',
  path: '/works/$workId/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsPostIdEditRoute = AdminPostsPostIdEditRouteImport.update({
  id: '/posts/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login-hub': typeof AdminLoginHubRoute
  '/dashboard': typeof DashboardRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/site': typeof AdminSiteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/works/': typeof WorksIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/works/new': typeof AdminWorksNewRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/works/': typeof AdminWorksIndexRoute
  '/admin/posts/$postId/edit': typeof AdminPostsPostIdEditRoute
  '/admin/works/$workId/edit': typeof AdminWorksWorkIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login-hub': typeof AdminLoginHubRoute
  '/dashboard': typeof DashboardRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/site': typeof AdminSiteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/works': typeof WorksIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/works/new': typeof AdminWorksNewRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/works': typeof AdminWorksIndexRoute
  '/admin/posts/$postId/edit': typeof AdminPostsPostIdEditRoute
  '/admin/works/$workId/edit': typeof AdminWorksWorkIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login-hub': typeof AdminLoginHubRoute
  '/dashboard': typeof DashboardRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/site': typeof AdminSiteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/works/': typeof WorksIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/works/new': typeof AdminWorksNewRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/works/': typeof AdminWorksIndexRoute
  '/admin/posts/$postId/edit': typeof AdminPostsPostIdEditRoute
  '/admin/works/$workId/edit': typeof AdminWorksWorkIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login-hub'
    | '/dashboard'
    | '/admin/profile'
    | '/admin/site'
    | '/blog/$slug'
    | '/works/$workId'
    | '/admin/'
    | '/blog/'
    | '/works/'
    | '/admin/posts/new'
    | '/admin/works/new'
    | '/admin/categories/'
    | '/admin/posts/'
    | '/admin/works/'
    | '/admin/posts/$postId/edit'
    | '/admin/works/$workId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login-hub'
    | '/dashboard'
    | '/admin/profile'
    | '/admin/site'
    | '/blog/$slug'
    | '/works/$workId'
    | '/admin'
    | '/blog'
    | '/works'
    | '/admin/posts/new'
    | '/admin/works/new'
    | '/admin/categories'
    | '/admin/posts'
    | '/admin/works'
    | '/admin/posts/$postId/edit'
    | '/admin/works/$workId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login-hub'
    | '/dashboard'
    | '/admin/profile'
    | '/admin/site'
    | '/blog/$slug'
    | '/works/$workId'
    | '/admin/'
    | '/blog/'
    | '/works/'
    | '/admin/posts/new'
    | '/admin/works/new'
    | '/admin/categories/'
    | '/admin/posts/'
    | '/admin/works/'
    | '/admin/posts/$postId/edit'
    | '/admin/works/$workId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginHubRoute: typeof AdminLoginHubRoute
  DashboardRoute: typeof DashboardRoute
  BlogSlugRoute: typeof BlogSlugRoute
  WorksWorkIdRoute: typeof WorksWorkIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  WorksIndexRoute: typeof WorksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login-hub': {
      id: '/admin-login-hub'
      path: '/admin-login-hub'
      fullPath: '/admin-login-hub'
      preLoaderRoute: typeof AdminLoginHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/': {
      id: '/works/'
      path: '/works'
      fullPath: '/works/'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/works/$workId': {
      id: '/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof WorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/works/': {
      id: '/admin/works/'
      path: '/works'
      fullPath: '/admin/works/'
      preLoaderRoute: typeof AdminWorksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/works/new': {
      id: '/admin/works/new'
      path: '/works/new'
      fullPath: '/admin/works/new'
      preLoaderRoute: typeof AdminWorksNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/works/$workId/edit': {
      id: '/admin/works/$workId/edit'
      path: '/works/$workId/edit'
      fullPath: '/admin/works/$workId/edit'
      preLoaderRoute: typeof AdminWorksWorkIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/$postId/edit': {
      id: '/admin/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/admin/posts/$postId/edit'
      preLoaderRoute: typeof AdminPostsPostIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSiteRoute: typeof AdminSiteRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminWorksNewRoute: typeof AdminWorksNewRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminWorksIndexRoute: typeof AdminWorksIndexRoute
  AdminPostsPostIdEditRoute: typeof AdminPostsPostIdEditRoute
  AdminWorksWorkIdEditRoute: typeof AdminWorksWorkIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProfileRoute: AdminProfileRoute,
  AdminSiteRoute: AdminSiteRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminWorksNewRoute: AdminWorksNewRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminWorksIndexRoute: AdminWorksIndexRoute,
  AdminPostsPostIdEditRoute: AdminPostsPostIdEditRoute,
  AdminWorksWorkIdEditRoute: AdminWorksWorkIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginHubRoute: AdminLoginHubRoute,
  DashboardRoute: DashboardRoute,
  BlogSlugRoute: BlogSlugRoute,
  WorksWorkIdRoute: WorksWorkIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  WorksIndexRoute: WorksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
