/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksIndexRouteImport } from './routes/works/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WorksWorkIdRouteImport } from './routes/works/$workId'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminWorksIndexRouteImport } from './routes/admin/works/index'
import { Route as AdminWorksNewRouteImport } from './routes/admin/works/new'
import { Route as AdminWorksWorkIdEditRouteImport } from './routes/admin/works/$workId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIndexRoute = WorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WorksWorkIdRoute = WorksWorkIdRouteImport.update({
  id: '/works/$workId',
  path: '/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorksIndexRoute = AdminWorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorksNewRoute = AdminWorksNewRouteImport.update({
  id: '/works/new',
  path: '/works/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorksWorkIdEditRoute = AdminWorksWorkIdEditRouteImport.update({
  id: '/works/$workId/edit',
  path: '/works/$workId/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/admin/': typeof AdminIndexRoute
  '/works/': typeof WorksIndexRoute
  '/admin/works/new': typeof AdminWorksNewRoute
  '/admin/works/': typeof AdminWorksIndexRoute
  '/admin/works/$workId/edit': typeof AdminWorksWorkIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/admin': typeof AdminIndexRoute
  '/works': typeof WorksIndexRoute
  '/admin/works/new': typeof AdminWorksNewRoute
  '/admin/works': typeof AdminWorksIndexRoute
  '/admin/works/$workId/edit': typeof AdminWorksWorkIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/admin/': typeof AdminIndexRoute
  '/works/': typeof WorksIndexRoute
  '/admin/works/new': typeof AdminWorksNewRoute
  '/admin/works/': typeof AdminWorksIndexRoute
  '/admin/works/$workId/edit': typeof AdminWorksWorkIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/admin/profile'
    | '/works/$workId'
    | '/admin/'
    | '/works/'
    | '/admin/works/new'
    | '/admin/works/'
    | '/admin/works/$workId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/admin/profile'
    | '/works/$workId'
    | '/admin'
    | '/works'
    | '/admin/works/new'
    | '/admin/works'
    | '/admin/works/$workId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/admin/profile'
    | '/works/$workId'
    | '/admin/'
    | '/works/'
    | '/admin/works/new'
    | '/admin/works/'
    | '/admin/works/$workId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  WorksWorkIdRoute: typeof WorksWorkIdRoute
  WorksIndexRoute: typeof WorksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/': {
      id: '/works/'
      path: '/works'
      fullPath: '/works/'
      preLoaderRoute: typeof WorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/works/$workId': {
      id: '/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof WorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/works/': {
      id: '/admin/works/'
      path: '/works'
      fullPath: '/admin/works/'
      preLoaderRoute: typeof AdminWorksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/works/new': {
      id: '/admin/works/new'
      path: '/works/new'
      fullPath: '/admin/works/new'
      preLoaderRoute: typeof AdminWorksNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/works/$workId/edit': {
      id: '/admin/works/$workId/edit'
      path: '/works/$workId/edit'
      fullPath: '/admin/works/$workId/edit'
      preLoaderRoute: typeof AdminWorksWorkIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminProfileRoute: typeof AdminProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminWorksNewRoute: typeof AdminWorksNewRoute
  AdminWorksIndexRoute: typeof AdminWorksIndexRoute
  AdminWorksWorkIdEditRoute: typeof AdminWorksWorkIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProfileRoute: AdminProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminWorksNewRoute: AdminWorksNewRoute,
  AdminWorksIndexRoute: AdminWorksIndexRoute,
  AdminWorksWorkIdEditRoute: AdminWorksWorkIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  WorksWorkIdRoute: WorksWorkIdRoute,
  WorksIndexRoute: WorksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
